### ISSUE TITLE
Error installing phook with Linuxbrew

### ISSUE THREAD

**Issue by OmeGak** [TheFox/homebrew-brewery#3]
Failed to install phook on a clean Ubuntu 14.04 install with Linuxbrew.

```console
==> Installing phook from thefox/brewery
==> Installing dependencies for thefox/brewery/phook: make
==> Installing thefox/brewery/phook dependency: make
==> Downloading https://ftp.gnu.org/gnu/make/make-4.2.1.tar.bz2
==> ./configure --prefix=/home/omegak/.linuxbrew/Cellar/make/4.2.1_1
==> make install
🍺  /home/omegak/.linuxbrew/Cellar/make/4.2.1_1: 38 files, 2.6MB, built in 32 seconds
==> Installing thefox/brewery/phook 
==> Downloading https://github.com/drinchev/phook/archive/v0.0.3.tar.gz
==> Downloading from https://codeload.github.com/drinchev/phook/tar.gz/v0.0.3
==> make
Last 15 lines from /home/omegak/.cache/Homebrew/Logs/phook/01.make:
2017-05-13 10:42:09 +0200

make

phook.c:13:23: fatal error: sys/event.h: No such file or directory
 #include <sys/event.h>
                       ^
compilation terminated.
make[1]: *** [Makefile:4: phook] Error 1
```

**Comment by TheFox** [comment]
I think this was my fault. In fc9176edf141cf46dfeabe72b1cc3af690ff56c5 something went wrong. I reverted the current version back to Phook v0.0.3, which is wrong. The newest version is v0.0.6. As you can see here: https://github.com/drinchev/phook/releases

- Beside that, which Brew version do you use?
- Did you run `brew update`?
- Did you try to compile phook vom source? See [README](https://github.com/drinchev/phook/blob/ed71aec28b4c1c02f70c95ba571a9db4ade8e67e/README.md).

Seams that you miss some development header files. I don't know Ubuntu.

**Comment by OmeGak** [comment]
Just run `brew update` and it fetched v0.0.6. The problem remains, still.

```console
$ brew --version
Homebrew 1.1.12
Homebrew/homebrew-core (git revision 25de; last commit 2017-05-12)
```

I've also tried to compile phook from source and still the same problem. Also with the non-brewed `make`.

```console
$ /usr/bin/make install
gcc -o phook phook.c 
phook.c:12:23: fatal error: sys/event.h: No such file or directory
 #include <sys/event.h>
                       ^
compilation terminated.
make: *** [phook] Error 1
```

**Comment by TheFox** [comment]
Please post this issue to [phook](https://github.com/drinchev/phook/issues). I don't know what you need to compile phook under Ubuntu. Maybe some dev headers for C/C++ (development environment).

**Comment by OmeGak** [comment]
Moved the issue to phook repo. https://github.com/drinchev/phook/issues/5

**Comment by OmeGak** [comment]
So it seems I missed the part where it says `phook` only works in macOS. Is there, perhaps, a way to specify a formula not being available for Linux?
