### ISSUE TITLE
Updating phook to 0.0.7

### ISSUE THREAD

**Issue by drinchev** [TheFox/homebrew-brewery#4]
Hello,

Thanks for your brew tap.

I just released v0.0.7 of phook, which fixes https://github.com/drinchev/phook/issues/7. 

Can you please update the script to fetch the latest version :)

Thanks a LOT!

### Emotional State

My emotional state right now is:

- [X] Excited :smile:
- [ ] Confused :confused:
- [ ] Worried :worried:
- [ ] Upset :angry:
- [ ] Panicked :scream:
- [ ] Angry :rage:

**Comment by TheFox** [comment]
Have a look at this: d3f0837a0d9655f0be009c3c1672f8ffaf75015a
