### ISSUE TITLE
Calling plist_options is deprecated. Use service.require_root instead.

### ISSUE THREAD

**Issue by yougotwill** [TheFox/homebrew-brewery#9]
### Emotional State

My emotional state right now is:

- [x] Excited :smile:
- [ ] Confused :confused:
- [ ] Worried :worried:
- [ ] Upset :angry:
- [ ] Panicked :scream:
- [ ] Angry :rage:

Homebrew returned this error

```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the thefox/brewery tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/thefox/homebrew-brewery/cmus-control.rb:30
```

P.S. Thank you for making cmus-control! 👍

**Comment by TheFox** [comment]
Thank you for reporting. Will fix it.

**Comment by TheFox** [comment]
@yougotwill I fixed it. Can you verify it's not showing the error anymore? I tried it using `brew reinstall --build-from-source cmus-control`.

**Comment by yougotwill** [comment]
@TheFox Confirmed that the error is not showing up after running the command above 👍
